### ISSUE TITLE
TGATE v0.1.1 encounter ValueError when performing multiple forward inferences

### ISSUE THREAD

**Issue by colorjam** [HaozheLiu-ST/T-GATE#10]
Hi! Thank you for the amazing work.

I encounter the ValueError when performing multiple forward inferences:
![image](https://github.com/HaozheLiu-ST/T-GATE/assets/23700012/047c1519-24f5-499c-9449-13dc9e8a252c)

Here's the testing code I used:
```
pipe = TgateSDLoader(
            pipe,
            gate_step=gate_step,
            num_inference_steps=inference_step
       ).to("cuda")
start_time = time.time()
for _ in range(infer_times):
    tagate_image = pipe.tgate(
          prompt,
          gate_step=gate_step,
          num_inference_steps=inference_step
      ).images    
    latency = (time.time() - start_time) / infer_times
    logging.info("T-GATE: {:.2f} seconds".format(latency))
```

Hope you can resolve this issue.

**Comment by greasebig** [comment]
same.
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by greasebig** [comment]
1731 if ip_adapter_image is not None or ip_adapter_image_embeds is not None:
   1732     added_cond_kwargs["image_embeds"] = image_embeds
...
--> 184         hidden_uncond, hidden_pred_text = hidden_states.chunk(2)
    185         cache = (hidden_uncond + hidden_pred_text ) / 2
    187 if input_ndim == 4:

ValueError: not enough values to unpack (expected 2, got 1)

**Comment by greasebig** [comment]
your T-GATE can only be used in sd1.5 sd2.1

**Comment by HaozheLiu-ST** [comment]
@colorjam which model and which pipeline do you use? We will shortly have a try in our local node.

**Comment by HaozheLiu-ST** [comment]
> your T-GATE can only be used in sd1.5 sd2.1
 
There might be some customized pipelines based on the same model. However, they may also revise the `__call__()`; we encourage the community to contribute TGATE to these methods. We cannot support all methods by ourselves. 
This is also why we provide [simple code](https://github.com/HaozheLiu-ST/T-GATE/tree/main/SD_2_1), where developers can easily integrate it into their code base. 
 
We sincerely thank you for your attention, recognition, understanding, and potential contribution.

**Comment by WentianZhang-ML** [comment]
Hi @colorjam and @greasebig, thanks again for your attention. We have addressed this issue. 

Please update the `tgate` to version 0.1.2 by `pip install -U tgate`  and try again.

**Comment by WentianZhang-ML** [comment]
> your T-GATE can only be used in sd1.5 sd2.1

Hi @greasebig, if you still have problems with these pipelines, please give me your completed code and log files.

BTW, if you want to contribute TGATE to other pipelines, please feel free to open a PR. We welcome all contributions from the community.
