### ISSUE TITLE
confusion about speedup

### ISSUE THREAD

**Issue by Peyton-Chen** [HaozheLiu-ST/T-GATE#13]
Hello, thank you for your excellent work. Your work considers the redundancy of crossattn and uses the cache approach to solve the above problem, and finally achieves the speedup of the generation. As far as I know, the computational cost of self-attn and ffn is larger than that of cross-attn. However, it is pointed out in the paper that t-gate can achieve nearly 40% speedup with only cache cross-attn.  How such a high speedup is achieved, if I have some misunderstanding of the technology.  I would appreciate it if you could help me solve this confusion. Thanks! :rose:

**Comment by HaozheLiu-ST** [comment]
Thanks for your attention and recognition. 🌹 

In the recent version, the improvement of efficiency comes from two aspects: i) Cross-attention is redundant during the fidelity-improving stage, and thus bypassing it can reduce the computation. ii) By caching and reusing cross-attention in the fidelity-improving stage, the conditional batch in classifier-free guidance is naturally removed from the computation graph to reduce computation costs.  

For a detailed analysis of improvements attributed solely to cross-attention, please refer to our case study on accelerating the consistency model.

Additionally, we acknowledge that self-attention is a critical bottleneck for latency. We have developed a strategy to remove self-attention from the computation graph, which halves the computation resources without the need for fine-tuning. The technical report and code are currently undergoing internal processing. Updates will be provided shortly. 

Please stay tuned! 😃

**Comment by Peyton-Chen** [comment]
Thank you for your quick and patient response! I agree with what you said. But take a pure dit architecture like pixart-alpha for example. The computation of cross-attn accounts for about 10% of the transformer block, and even caching all cross-attn achieves at most 10% speedup. So how to achieve 40% speedup in the paper? This is the point that puzzles me the most. I don't know if I overlooked an important detail or if there was some misunderstanding. Thank you very much for your answer. Thanks! :rose:

**Comment by HaozheLiu-ST** [comment]
Please also consider the impact of Classifier Free Guidance (CFG). CFG is a technology extensively employed in text-conditional diffusion models. CFG integrates two batches to guide conditional information. However, our findings indicate that cross-attention is, to some extent, useless during the fidelity-improving stage, motivating us to freeze its predictions as placeholders during inference. Consequently, CFG is also naturally ineffective in this scenario, leading us to eliminate the two-batch process associated with CFG to accelerate inference further. This is another reason that we can achieve almost a 40% speedup. 

For more details, see Eq. 6 in the technical report.

**Comment by Peyton-Chen** [comment]
Thank you for your reply! My confusion is solved. Thanks again!

**Comment by xduzhangjiayu** [comment]
> Thanks for your attention and recognition. 🌹
> 
> In the recent version, the improvement of efficiency comes from two aspects: i) Cross-attention is redundant during the fidelity-improving stage, and thus bypassing it can reduce the computation. ii) By caching and reusing cross-attention in the fidelity-improving stage, the conditional batch in classifier-free guidance is naturally removed from the computation graph to reduce computation costs.
> 
> For a detailed analysis of improvements attributed solely to cross-attention, please refer to our case study on accelerating the consistency model.
> 
> Additionally, we acknowledge that self-attention is a critical bottleneck for latency. We have developed a strategy to remove self-attention from the computation graph, which halves the computation resources without the need for fine-tuning. The technical report and code are currently undergoing internal processing. Updates will be provided shortly.
> 
> Please stay tuned! 😃

Hello,
Have you tried control-net like model support T-GATE?
