### ISSUE TITLE
About turbo model or lightning model.

### ISSUE THREAD

**Issue by ApolloRay** [HaozheLiu-ST/T-GATE#3]
Therefore, it is actually difficult to improve the speed of models with very few noise reduction steps, such as turbo or lightning models.

**Comment by HaozheLiu-ST** [comment]
Thanks for your attention to our work. 
﻿
As the reported result of LCM, in very few steps of generation, our method can reduce ~10% computation cost for a single image. We believe for a model that may be called for billions of times daily, it is still a non-negligible reduction. 
﻿
We agree with you that it is more challenging to further improve a distilled diffusion model. 
﻿
However, TGATE is also applicable to the distilling process. Our method can accelerate the generation process of the teacher model, thereby further accelerating the training of the student model. 
﻿
Last but not least, Tgate is a free lunch without training costs and performance drops, so please try TGATE to save your time and cost.

**Comment by ApolloRay** [comment]
> Thanks for your attention to our work. ﻿ As the reported result of LCM, in very few steps of generation, our method can reduce ~10% computation cost for a single image. We believe for a model that may be called for billions of times daily, it is still a non-negligible reduction. ﻿ We agree with you that it is more challenging to further improve a distilled diffusion model. ﻿ However, TGATE is also applicable to the distilling process. Our method can accelerate the generation process of the teacher model, thereby further accelerating the training of the student model. ﻿ Last but not least, Tgate is a free lunch without training costs and performance drops, so please try TGATE to save your time and cost.

Yes, I agree with it.

**Comment by ApolloRay** [comment]
And pixart-sigma is released, if you have enough time, I hope you can try it.

**Comment by HaozheLiu-ST** [comment]
Thanks for your suggestions. We plan to have a try soon. Stay tuned!

**Comment by HaozheLiu-ST** [comment]
Hello, we have tested our method on PixArt Sigma. It works well. Please see our implementation on [diffusers](https://huggingface.co/docs/diffusers/main/en/optimization/tgate). We will provide a tutorial for this model once it is officially supported by diffusers.
