### ISSUE TITLE
This is truly an amazing discovery

### ISSUE THREAD

**Issue by Songssx** [HaozheLiu-ST/T-GATE#4]
May I ask if you are planning to pull the ComfyUI project and add this important research to ComfyUI？

**Comment by HaozheLiu-ST** [comment]
Thanks for your recognition. 

We plan to first incorporate this acceleration method into diffusers. Then, we will explore the potential opportunity for contributing to ComflyUI. But this is not guaranteed.

**Comment by rdcoder33** [comment]
Can we use custom scripts to add T-GATE to ComfyUI

**Comment by HaozheLiu-ST** [comment]
Sure, it is ok for us. We welcome all contributions from the community. Just make sure to provide a link to our GitHub for credit assignment.

**Comment by HaozheLiu-ST** [comment]
Hello, we thank the community's (@JettHu) contribution, please see the [re-implementation](https://github.com/JettHu/ComfyUI_TGate) on comfyUI.
