### ISSUE TITLE
how to use in PixArt-LCM-XL-2-1024-MS  model?

### ISSUE THREAD

**Issue by lonngxiang** [HaozheLiu-ST/T-GATE#5]

**Comment by HaozheLiu-ST** [comment]
Hello, please have a look at [the main file](https://github.com/HaozheLiu-ST/T-GATE?tab=readme-ov-file#-usage), we provide an option `lcm_pixart ` as a demo. Please have a try.

**Comment by lonngxiang** [comment]
Very good work, but the effect seems to be less than the original

prompt = "A small cactus with a happy face in the Sahara desert."

```
 --model 'lcm_pixart'  --gate_step 1 --saved_path './aaa.png'  --inference_step 4
```
![image](https://github.com/HaozheLiu-ST/T-GATE/assets/40717349/5746f442-17af-4654-9349-b22e6e89e855)

original

![image](https://github.com/HaozheLiu-ST/T-GATE/assets/40717349/e23647fe-c8d4-40f7-b015-c233cce892b6)

**Comment by HaozheLiu-ST** [comment]
![test](https://github.com/HaozheLiu-ST/T-GATE/assets/53887227/da915c7f-89fc-4e4f-8295-f85afae1e004)
I generated it again by using the same caption and hyperparameters, but it seems ok; I guess different random seeds lead to different results. You can try other initial noises. Another important parameter is the gate step; you can set it larger to make it more similar to the original one.

**Comment by HaozheLiu-ST** [comment]
My manual seed is randomly set as `generator = torch.manual_seed('10086')`.

**Comment by lonngxiang** [comment]
I employ "pipe.enable_model_cpu_offload" to operate, and I did not utilize the seed; the larger the inference_step value becomes, the better it is.

![image](https://github.com/HaozheLiu-ST/T-GATE/assets/40717349/7a0b6d72-e2bf-4237-9f5b-c7c2773fa43e)

**Comment by lonngxiang** [comment]
> generator = torch.manual_seed('10086')
 torch.manual_seed('10086') and inference_step=4

![image](https://github.com/HaozheLiu-ST/T-GATE/assets/40717349/111cc6cf-acf9-41b3-a746-7cfb4126a530)

**Comment by HaozheLiu-ST** [comment]
I don't know the reason, do you set the `guidance_scale=0.`? `pipe.enable_model_cpu_offload()` doesn't matter. 
I attached 3 images sampled randomly, I think it is ok and comparable with that of the base model. 
![test](https://github.com/HaozheLiu-ST/T-GATE/assets/53887227/7975a38f-afca-4734-a84d-fec510e4d197)
![test](https://github.com/HaozheLiu-ST/T-GATE/assets/53887227/310af098-cb9b-4782-8685-d0bba4358751)
![test](https://github.com/HaozheLiu-ST/T-GATE/assets/53887227/1ada5bf5-f334-49e2-a026-df70825c849f)

**Comment by lonngxiang** [comment]
no, just run command

···

python  main.py  --prompt 'A small cactus with a happy face in the Sahara desert'  --model 'lcm_pixart'  --gate_step 1 --saved_path 'aaa1.png'  --inference_step 4
···

**Comment by lonngxiang** [comment]
although set inference_step 10 ；It doesn't look perfect 

![image](https://github.com/HaozheLiu-ST/T-GATE/assets/40717349/1302a4c6-0035-4e60-ae52-a739102964e1)

**Comment by HaozheLiu-ST** [comment]
Thanks for your feedback. 
﻿
First, for the latent consistency model and based on the [existing empirical study](https://arxiv.org/abs/2310.04378), the optimal inference steps are 4-6. Increasing the inference steps may degrade the performance. 
﻿
Second, we agree that the LCM model is a little weaker than the original model; however, the inference can be accelerated significantly by LCM. If a perfect image is required, please have a try for PixArt-Alpha/Sigma. TGATE can also accelerate their inference. 
﻿
Third, I think you may try different initial noises to get a satisfactory generated result. Different initial noises may lead to different outcomes.  
﻿
Fourth, I would like to bring your attention to another hyperparameter, `gate step`.  
I have attached the visualization for you to look over. A larger `gate step` can get results that are similar to the original output.  All visualizations are based on the same input noise. 


![test_baseline](https://github.com/HaozheLiu-ST/T-GATE/assets/53887227/524b80ae-8625-4938-bc77-d80cc46a54a3)
> w/o using TGATE 

![test_ours](https://github.com/HaozheLiu-ST/T-GATE/assets/53887227/2601fe7e-6f79-4a36-8111-d28c73abe197)
>TGATE (gate step=1)

![test_ours_2](https://github.com/HaozheLiu-ST/T-GATE/assets/53887227/8cee8f89-3083-4fb1-ab83-4f4c9af01f10)
>TGATE (gate step=2)

I hope this can help you understand our method. Wish you have a good day.

**Comment by lonngxiang** [comment]
> gate step

big tks，i will have try
