### ISSUE TITLE
About Playground-v2.5-1024 model.

### ISSUE THREAD

**Issue by yiboz2001** [HaozheLiu-ST/T-GATE#6]
Hi! 
Thanks for your amazing work. 

Playground-v2.5-1024 is a stronger T2I model based on the SD-XL architecture.
(https://huggingface.co/playgroundai/playground-v2.5-1024px-aesthetic)
I try to use the follow code to speed up the model, but the result seems terrible.

```
import torch
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_pretrained(
        "playgroundai/playground-v2.5-1024px-aesthetic",
        torch_dtype=torch.float16,
        variant="fp16",
        use_safetensors=True,
)

from tgate import TgateSDXLLoader
gate_step = 10
inference_step = 25
pipe = TgateSDXLLoader(
       pipe,
       gate_step=gate_step,
       num_inference_steps=inference_step,
)
pipe = pipe.to("cuda")

prompt = "Astronaut in a jungle, cold color palette, muted colors, detailed, 8k."
        
image = pipe.tgate(
        prompt,
        gate_step=gate_step,
        num_inference_steps=inference_step
).images[0]
image.save(f"{prompt}.png") 
```
![Astronaut in a jungle, cold color palette, muted colors, detailed, 8k](https://github.com/HaozheLiu-ST/T-GATE/assets/148748624/fe675e89-af55-4a13-a603-d8eacaf74747)

Is there any way to solve the problem?
I am looking for your reply.

**Comment by WentianZhang-ML** [comment]
Hi, thanks for your attention! 

We supplemented the conditional check for denormalizing the latents in [L472](https://github.com/HaozheLiu-ST/T-GATE/blob/0.1.1/src/tgate/SDXL.py#L472) to solve the problem.  

Please upgrade the `tgate` to the version [0.1.1](https://github.com/HaozheLiu-ST/T-GATE/tree/0.1.1) by `pip install --upgrade tgate` and have a try again.

The example of [playgroundai](https://huggingface.co/playgroundai/playground-v2.5-1024px-aesthetic) sets num_inference_steps as 50, so we recommend setting gate_step as 25 or 30 when num_inference_steps is 50 for better results. 

BTW, you can also try `TgateSDXLDeepCacheLoader` to further improve the efficiency. 

If you find our work inspiring, please consider giving a star!

**Comment by yiboz2001** [comment]
> Hi, thanks for your attention!
> 
> We supplemented the conditional check for denormalizing the latents in [L472](https://github.com/HaozheLiu-ST/T-GATE/blob/0.1.1/src/tgate/SDXL.py#L472) to solve the problem.
> 
> Please upgrade the `tgate` to the version [0.1.1](https://github.com/HaozheLiu-ST/T-GATE/tree/0.1.1) by `pip install --upgrade tgate` and have a try again.
> 
> The example of [playgroundai](https://huggingface.co/playgroundai/playground-v2.5-1024px-aesthetic) sets num_inference_steps as 50, so we recommend setting gate_step as 25 or 30 when num_inference_steps is 50 for better results.
> 
> BTW, you can also try `TgateSDXLDeepCacheLoader` to further improve the efficiency.
> 
> If you find our work inspiring, please consider giving a star!

The new version works! Thanks again. 
Both TgateSDXLDeepCacheLoader and TgateSDXLLoader speed the process a lot with the same qualitity. 
I have starred all projects out of my respect!

**Comment by WentianZhang-ML** [comment]
Great, thank you so much！
