### ISSUE TITLE
Attempted to implement a comfyui node.

### ISSUE THREAD

**Issue by JettHu** [HaozheLiu-ST/T-GATE#8]
I tried to implement a version of comfyui's T-GATE but seemed to encounter some problems. The quality of the generated image declined after the apply the node. 
![企业微信截图_3ce8507a-d6ee-4b75-ad19-cf5d664d192d](https://github.com/HaozheLiu-ST/T-GATE/assets/35261585/aa0d0ea7-c060-443e-a914-72808f77897a)

![企业微信截图_2ff2a874-3fc5-489f-b587-404615d7b684](https://github.com/HaozheLiu-ST/T-GATE/assets/35261585/8eaf321e-fa48-4f93-a119-670728db24a2)

this is the repo: https://github.com/JettHu/ComfyUI_TGate

**Comment by WentianZhang-ML** [comment]
Hi, thanks for your attention to our work. 

I have gone through your repo. Please do not use TGATE on `"attn1"` and try again. 

`"attn1"` refers to the self-attention when `only_cross_attention` is set as _False_ (default config), but TGATE is only used to cache the cross-attention output

**Comment by JettHu** [comment]
> Hi, thanks for your attention to our work.
> 
> I have gone through your repo. Please do not use TGATE on `"attn1"` and try again.
> 
> `"attn1"` refers to the self-attention when `only_cross_attention` is set as _False_ (default config), but TGATE is only used to cache the cross-attention output

thx, i'll try it

**Comment by JettHu** [comment]
It works after I add a `only_cross_attention` switch! 
![tgate_workflow_example](https://github.com/HaozheLiu-ST/T-GATE/assets/35261585/369434d3-0dda-411c-83d0-ab34f573717f)

**Comment by WentianZhang-ML** [comment]
Sure, you can also set `only_cross_attention` as False and only use TGATE on `attn2`, which is closer to our pipeline.

**Comment by JettHu** [comment]
I'm going to close this issue
